server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 50

  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: validate

  session:
    redis:
      namespace: earth

--- # Jedis Pool Preferences
jedis:
  pool:
    max-idle: 50
    max-total: 200
    max-wait-millis: 5000


--- # HTTP Client Preferences
http-client:
  max-total: 200
  max-per-route: 20
  timeout:
    connect: 30000
    request: 30000
    socket: 30000
  keep-alive:
    duration: 30000

channel:
  wechatpay:
    url: https://api.mch.weixin.qq.com
