server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

--- # Jedis Pool Preferences
jedis:
  pool:
    max-idle: 50
    max-total: 200
    max-wait-millis: 5000
