server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 50

  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
