server:
  port: 10000

sidecar:
  port: 8000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1

zuul:
  prefix: /api
  routes:
    user:
      path: /users/**
      stripPrefix: false
      sensitiveHeaders: #Cookie,Set-Cookie,Authorization
    merchant:
      path: /merchants/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: user
    employee:
      path: /employees/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: user
    examination:
      path: /examinations/**
      stripPrefix: false
      sensitiveHeaders:
    registration:
      path: /registrations/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: examination
    order:
      path: /orders/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: payment
    secret:
      path: /secrets/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: payment

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
