server:
  port: 10000

sidecar:
  port: 8000

zuul:
  prefix: /api
  routes:
    user:
      path: /users/**
      stripPrefix: false
      sensitiveHeaders: #Cookie,Set-Cookie,Authorization
    examination:
      path: /examinations/**
      stripPrefix: false
      sensitiveHeaders:
    merchant:
      path: /merchants/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: examination
    registration:
      path: /registrations/**
      stripPrefix: false
      sensitiveHeaders:
      serviceId: examination

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
